In [1]:
import pandas as pd
applications = pd.read_csv("applications_raw.csv")
loans = pd.read_csv("loans_raw.csv")

# 1. Total applications
total_applications = applications["application_id"].nunique()

# 2. Approved applications
approved_applications = (
    applications[applications["application_status"] == "Approved"]
    ["application_id"].nunique()
)

# 3. Disbursed loans
disbursed_loans = loans["loan_id"].nunique()

# 4. Approval rate
approval_rate = approved_applications / total_applications * 100

# 5. Approval-to-disbursement rate
approval_to_disbursement = disbursed_loans / approved_applications * 100

# 6. Application-to-disbursement rate
application_to_disbursement = disbursed_loans / total_applications * 100

print("Total Applications:", total_applications)
print("Approved Applications:", approved_applications)
print("Disbursed Loans:", disbursed_loans)
print("Approval Rate:", round(approval_rate, 2), "%")
print("Approval → Disbursement:", round(approval_to_disbursement, 2), "%")
print("Application → Disbursement:", round(application_to_disbursement, 2), "%")

Total Applications: 100000
Approved Applications: 54113
Disbursed Loans: 48702
Approval Rate: 54.11 %
Approval → Disbursement: 90.0 %
Application → Disbursement: 48.7 %

In [2]:
total_requested = applications["requested_amount"].sum()

total_approved = applications["approved_amount"].sum()

total_disbursed = loans["disbursement_amount"].sum()

avg_requested = applications["requested_amount"].mean()

avg_disbursed = loans["disbursement_amount"].mean()

print("Total Requested: ₹", round(total_requested, 2))
print("Total Approved: ₹", round(total_approved, 2))
print("Total Disbursed: ₹", round(total_disbursed, 2))
print("Average Requested: ₹", round(avg_requested, 2))
print("Average Disbursed: ₹", round(avg_disbursed, 2))

Total Requested: ₹ 21132552800.0
Total Approved: ₹ 8513932000.0
Total Disbursed: ₹ 7271933000.0
Average Requested: ₹ 211009.01
Average Disbursed: ₹ 149314.87

In [3]:
customers["customer_type"].value_counts()
customers["employment_type"].value_counts()
customers["region"].value_counts()
customers["monthly_income"].describe()
customers["age"].describe()

NameError: name 'customers' is not defined

In [4]:
import pandas as pd

customers = pd.read_csv("customers_raw.csv")

In [5]:
print("Customer Type:")
print(customers["customer_type"].value_counts())

print("\nEmployment Type:")
print(customers["employment_type"].value_counts())

print("\nRegion:")
print(customers["region"].value_counts())

print("\nMonthly Income:")
print(customers["monthly_income"].describe())

print("\nAge:")
print(customers["age"].describe())

Customer Type:
customer_type
New         29089
Existing    21011
Name: count, dtype: int64

Employment Type:
employment_type
Salaried          24992
Self-Employed     10089
Business Owner     8929
Contract           4025
Student            2065
Name: count, dtype: int64

Region:
region
South    16182
West     13550
North    11363
Other     5539
East      3466
Name: count, dtype: int64

Monthly Income:
count     49950.000000
mean      52377.045946
std       31361.105828
min      -49569.000000
25%       31044.000000
50%       44978.500000
75%       65313.000000
max      350000.000000
Name: monthly_income, dtype: float64

Age:
count    50100.000000
mean        40.480299
std         11.552372
min         21.000000
25%         30.000000
50%         41.000000
75%         50.000000
max         60.000000
Name: age, dtype: float64

In [6]:
applications = pd.read_csv("applications_raw.csv")

customer_app = applications.merge(
    customers[["customer_id", "customer_type"]],
    on="customer_id",
    how="left"
)

customer_type_analysis = (
    customer_app.groupby("customer_type")
    .agg(
        applications=("application_id", "nunique"),
        approved=("application_status", lambda x: (x == "Approved").sum())
    )
)

customer_type_analysis["approval_rate"] = (
    customer_type_analysis["approved"]
    / customer_type_analysis["applications"] * 100
)

customer_type_analysis

               applications  approved  approval_rate
customer_type
Existing              41797     31259      74.787664
New                   58203     23035      39.576998

In [7]:
credit = pd.read_csv("credit_assessments_raw.csv")

credit["credit_score"].describe()

count    100000.000000
mean        691.934920
std          65.876132
min         250.000000
25%         648.000000
50%         692.000000
75%         737.000000
max         999.000000
Name: credit_score, dtype: float64

In [8]:
bins = [299, 549, 649, 699, 749, 850]
labels = [
    "High Risk",
    "Moderate Risk",
    "Medium Risk",
    "Low Risk",
    "Very Low Risk"
]

credit["risk_band"] = pd.cut(
    credit["credit_score"],
    bins=bins,
    labels=labels
)

credit["risk_band"].value_counts().sort_index()

risk_band
High Risk         1542
Moderate Risk    24343
Medium Risk      28539
Low Risk         26308
Very Low Risk    19243
Name: count, dtype: int64

In [9]:
apps_unique = applications.drop_duplicates(subset="application_id")

credit_analysis = apps_unique.merge(
    credit[["application_id", "risk_band"]],
    on="application_id",
    how="left"
)

approval_by_risk = (
    credit_analysis.dropna(subset=["risk_band"])
    .groupby("risk_band", observed=False)
    .agg(
        applications=("application_id", "nunique"),
        approved=("application_status",
                   lambda x: (x == "Approved").sum())
    )
)

approval_by_risk["approval_rate"] = (
    approval_by_risk["approved"]
    / approval_by_risk["applications"] * 100
)

approval_by_risk

               applications  approved  approval_rate
risk_band
High Risk              1542         0       0.000000
Moderate Risk         24343      4387      18.021608
Medium Risk           28539     16953      59.402922
Low Risk              26308     15847      60.236430
Very Low Risk         19243     16913      87.891701

In [1]:
import pandas as pd
repayments = pd.read_csv("repayments_raw.csv")

In [2]:
repayments.shape

(465982, 12)

In [6]:
bins = [299, 549, 649, 699, 749, 850]
labels = [
    "High Risk",
    "Moderate Risk",
    "Medium Risk",
    "Low Risk",
    "Very Low Risk"
]

credit["risk_band"] = pd.cut(
    credit["credit_score"],
    bins=bins,
    labels=labels
)

In [7]:
credit["risk_band"].value_counts(dropna=False)

risk_band
Medium Risk      28539
Low Risk         26308
Moderate Risk    24343
Very Low Risk    19243
High Risk         1542
NaN                 25
Name: count, dtype: int64

In [ ]:

import pandas as pd

applications = pd.read_csv("applications_raw.csv")
loans = pd.read_csv("loans_raw.csv")
credit = pd.read_csv("credit_assessments_raw.csv")
repayments = pd.read_csv("repayments_raw.csv")
loans_unique = loans.drop_duplicates("loan_id")

loan_risk = (
    loans_unique
    .merge(
        applications.drop_duplicates("application_id")[
            ["application_id", "customer_id"]
        ],
        on="application_id",
        how="left"
    )
    .merge(
        credit[["application_id", "risk_band"]],
        on="application_id",
        how="left"
    )
)

loan_default = (
    repayments.groupby("loan_id")["default_flag"]
    .max()
    .reset_index()
)

loan_risk = loan_risk.merge(
    loan_default,
    on="loan_id",
    how="left"
)

default_by_risk = (
    loan_risk.dropna(subset=["risk_band"])
    .groupby("risk_band", observed=False)
    .agg(
        loans=("loan_id", "nunique"),
        defaulted_loans=("default_flag", "sum")
    )
)

default_by_risk["default_rate"] = (
    default_by_risk["defaulted_loans"]
    / default_by_risk["loans"] * 100
)

default_by_risk

In [9]:
loans_unique = loans.drop_duplicates("loan_id")

loan_risk = (
    loans_unique
    .merge(
        applications.drop_duplicates("application_id")[
            ["application_id", "customer_id"]
        ],
        on="application_id",
        how="left"
    )
    .merge(
        credit[["application_id", "risk_band"]],
        on="application_id",
        how="left"
    )
)

loan_default = (
    repayments.groupby("loan_id")["default_flag"]
    .max()
    .reset_index()
)

loan_risk = loan_risk.merge(
    loan_default,
    on="loan_id",
    how="left"
)

default_by_risk = (
    loan_risk.dropna(subset=["risk_band"])
    .groupby("risk_band", observed=False)
    .agg(
        loans=("loan_id", "nunique"),
        defaulted_loans=("default_flag", "sum")
    )
)

default_by_risk["default_rate"] = (
    default_by_risk["defaulted_loans"]
    / default_by_risk["loans"] * 100
)

default_by_risk

KeyError: "['risk_band'] not in index"

In [10]:
import pandas as pd

# Load datasets
applications = pd.read_csv("applications_raw.csv")
loans = pd.read_csv("loans_raw.csv")
credit = pd.read_csv("credit_assessments_raw.csv")
repayments = pd.read_csv("repayments_raw.csv")

# Create risk bands
bins = [299, 549, 649, 699, 749, 850]
labels = [
    "High Risk",
    "Moderate Risk",
    "Medium Risk",
    "Low Risk",
    "Very Low Risk"
]

credit["risk_band"] = pd.cut(
    credit["credit_score"],
    bins=bins,
    labels=labels
)

# Remove duplicate loan/application records
loans_unique = loans.drop_duplicates("loan_id")
applications_unique = applications.drop_duplicates("application_id")

# Connect loans with risk bands
loan_risk = (
    loans_unique
    .merge(
        applications_unique[["application_id", "customer_id"]],
        on="application_id",
        how="left"
    )
    .merge(
        credit[["application_id", "risk_band"]],
        on="application_id",
        how="left"
    )
)

# Determine whether each loan ever reached default
loan_default = (
    repayments.groupby("loan_id")["default_flag"]
    .max()
    .reset_index()
)

# Add default information
loan_risk = loan_risk.merge(
    loan_default,
    on="loan_id",
    how="left"
)

# Calculate default rate by risk band
default_by_risk = (
    loan_risk
    .dropna(subset=["risk_band"])
    .groupby("risk_band", observed=False)
    .agg(
        loans=("loan_id", "nunique"),
        defaulted_loans=("default_flag", "sum")
    )
)

default_by_risk["default_rate"] = (
    default_by_risk["defaulted_loans"]
    / default_by_risk["loans"] * 100
)

default_by_risk

               loans  defaulted_loans  default_rate
risk_band
High Risk          0              0.0           NaN
Moderate Risk   3954            262.0      6.626201
Medium Risk    15202            891.0      5.861071
Low Risk       14303            719.0      5.026917
Very Low Risk  15231            658.0      4.320137

In [12]:
customers = pd.read_csv("customers_raw.csv")
loan_customer = (
    loans_unique
    .merge(
        applications_unique[["application_id", "customer_id"]],
        on="application_id",
        how="left"
    )
    .merge(
        customers[["customer_id", "customer_type"]],
        on="customer_id",
        how="left"
    )
    .merge(
        loan_default,
        on="loan_id",
        how="left"
    )
)

default_by_customer_type = (
    loan_customer
    .groupby("customer_type")
    .agg(
        loans=("loan_id", "nunique"),
        defaulted_loans=("default_flag", "sum")
    )
)

default_by_customer_type["default_rate"] = (
    default_by_customer_type["defaulted_loans"]
    / default_by_customer_type["loans"] * 100
)

default_by_customer_type

               loans  defaulted_loans  default_rate
customer_type
Existing       28029           1327.0      4.734382
New            20673           1209.0      5.848208

In [13]:
default_by_employment = (
    loan_customer
    .merge(
        customers[["customer_id", "employment_type"]],
        on="customer_id",
        how="left"
    )
    .groupby("employment_type")
    .agg(
        loans=("loan_id", "nunique"),
        defaulted_loans=("default_flag", "sum")
    )
)

default_by_employment["default_rate"] = (
    default_by_employment["defaulted_loans"]
    / default_by_employment["loans"] * 100
)

default_by_employment.sort_values("default_rate", ascending=False)

                 loans  defaulted_loans  default_rate
employment_type
Contract          3961            212.0      5.352184
Self-Employed     9673            509.0      5.262070
Student           1984            104.0      5.241935
Salaried         24273           1264.0      5.207432
Business Owner    8811            457.0      5.186698

In [14]:
default_by_channel = (
    loan_customer
    .merge(
        applications_unique[
            ["application_id", "acquisition_channel"]
        ],
        on="application_id",
        how="left"
    )
    .groupby("acquisition_channel")
    .agg(
        loans=("loan_id", "nunique"),
        defaulted_loans=("default_flag", "sum")
    )
)

default_by_channel["default_rate"] = (
    default_by_channel["defaulted_loans"]
    / default_by_channel["loans"] * 100
)

default_by_channel.sort_values("default_rate", ascending=False)

                     loans  defaulted_loans  default_rate
acquisition_channel
Partner               8728            512.0      5.866178
Referral              5878            320.0      5.444029
Direct                9634            508.0      5.272991
Digital Marketing     9717            485.0      4.991252
Mobile App           14575            707.0      4.850772
mobile app              24              1.0      4.166667
Digital marketing       26              0.0      0.000000
PARTNER                 15              0.0      0.000000

In [15]:
default_by_loan_type = (
    loan_customer
    .merge(
        applications_unique[
            ["application_id", "loan_type"]
        ],
        on="application_id",
        how="left"
    )
    .groupby("loan_type")
    .agg(
        loans=("loan_id", "nunique"),
        defaulted_loans=("default_flag", "sum")
    )
)

default_by_loan_type["default_rate"] = (
    default_by_loan_type["defaulted_loans"]
    / default_by_loan_type["loans"] * 100
)

default_by_loan_type.sort_values("default_rate", ascending=False)

           loans  defaulted_loans  default_rate
loan_type
Personal   23666           1262.0      5.332545
Business    9743            509.0      5.224264
Consumer   11879            597.0      5.025676
Education   3414            168.0      4.920914

In [16]:
loan_income = (
    loan_customer
    .merge(
        customers[["customer_id", "monthly_income"]],
        on="customer_id",
        how="left"
    )
)

loan_income["income_band"] = pd.cut(
    loan_income["monthly_income"],
    bins=[0, 30000, 50000, 75000, 100000, float("inf")],
    labels=[
        "Below 30K",
        "30K-50K",
        "50K-75K",
        "75K-100K",
        "100K+"
    ]
)

default_by_income = (
    loan_income
    .dropna(subset=["income_band"])
    .groupby("income_band", observed=False)
    .agg(
        loans=("loan_id", "nunique"),
        defaulted_loans=("default_flag", "sum")
    )
)

default_by_income["default_rate"] = (
    default_by_income["defaulted_loans"]
    / default_by_income["loans"] * 100
)

default_by_income

             loans  defaulted_loans  default_rate
income_band
Below 30K    10191            527.0      5.171230
30K-50K      16092            864.0      5.369128
50K-75K      12762            660.0      5.171603
75K-100K      5320            289.0      5.432331
100K+         4131            195.0      4.720407

In [17]:
# Sort repayments by loan and due date
repayments_sorted = repayments.sort_values(
    ["loan_id", "due_date"]
)

# Keep the latest repayment record for each loan
latest_repayment = (
    repayments_sorted
    .drop_duplicates("loan_id", keep="last")
)

# Check the result
latest_repayment.shape

(46116, 12)

In [18]:
dpd_analysis = (
    latest_repayment
    .groupby("dpd_bucket", observed=False)
    .agg(
        loans=("loan_id", "nunique"),
        overdue_amount=("overdue_amount", "sum"),
        outstanding_principal=("outstanding_principal", "sum")
    )
    .reset_index()
)

dpd_analysis

  dpd_bucket  loans  overdue_amount  outstanding_principal
0       1-30   1540     14233252.69           7.978636e+07
1      31-60   1065     11663414.72           5.452664e+07
2      61-89    284      3152501.16           1.532356e+07
3        90+    308      3234562.00           1.289669e+07
4    Current  42919            0.00           2.242675e+09

In [19]:

collections.head()

NameError: name 'collections' is not defined

In [20]:
collections = pd.read_csv("collections_raw.csv")

In [21]:
collections_summary = {
    "total_collection_actions": collections["collection_id"].nunique(),
    "total_amount_collected": collections["amount_collected"].sum(),
    "loans_with_collection_activity": collections["loan_id"].nunique()
}

collections_summary

{'total_collection_actions': 31477,
 'total_amount_collected': 124850079.83000001,
 'loans_with_collection_activity': 20815}

In [22]:
collection_actions = (
    collections
    .groupby("collection_action")
    .agg(
        actions=("collection_id", "nunique"),
        loans=("loan_id", "nunique"),
        amount_collected=("amount_collected", "sum")
    )
    .sort_values("amount_collected", ascending=False)
    .reset_index()
)

collection_actions

  collection_action  actions  loans  amount_collected
0              Call     9536   8266       37686699.04
1               SMS     9385   8155       36723152.38
2    Promise to Pay     6342   5780       25370890.06
3             Email     3731   3515       15238100.70
4   Field Follow-up     2483   2378        9831237.65

In [23]:
recovery_analysis = (
    collections
    .groupby("recovery_status")
    .agg(
        actions=("collection_id", "nunique"),
        loans=("loan_id", "nunique"),
        amount_collected=("amount_collected", "sum")
    )
    .sort_values("amount_collected", ascending=False)
    .reset_index()
)

recovery_analysis

  recovery_status  actions  loans  amount_collected
0         Partial    25674  18110       88217447.91
1       Recovered     5803   5321       36632631.92

In [24]:
applications["application_date"] = pd.to_datetime(
    applications["application_date"]
)

loans["disbursement_date"] = pd.to_datetime(
    loans["disbursement_date"]
)

monthly_applications = (
    applications
    .groupby(applications["application_date"].dt.to_period("M"))
    .agg(
        applications=("application_id", "nunique")
    )
    .reset_index()
)

monthly_applications["month"] = (
    monthly_applications["application_date"]
    .astype(str)
)

monthly_applications

   application_date  applications    month
0           2024-01          4246  2024-01
1           2024-02          3844  2024-02
2           2024-03          4263  2024-03
3           2024-04          4048  2024-04
4           2024-05          4196  2024-05
5           2024-06          4082  2024-06
6           2024-07          4331  2024-07
7           2024-08          4337  2024-08
8           2024-09          4118  2024-09
9           2024-10          4244  2024-10
10          2024-11          4168  2024-11
11          2024-12          4185  2024-12
12          2025-01          4278  2025-01
13          2025-02          3902  2025-02
14          2025-03          4287  2025-03
15          2025-04          4156  2025-04
16          2025-05          4252  2025-05
17          2025-06          4030  2025-06
18          2025-07          4272  2025-07
19          2025-08          4201  2025-08
20          2025-09          4117  2025-09
21          2025-10          4217  2025-10
22          2025-11          4007  2025-11
23          2025-12          4219  2025-12

In [25]:
monthly_disbursement = (
    loans
    .groupby(loans["disbursement_date"].dt.to_period("M"))
    .agg(
        loans=("loan_id", "nunique"),
        disbursement_amount=("disbursement_amount", "sum")
    )
    .reset_index()
)

monthly_disbursement["month"] = (
    monthly_disbursement["disbursement_date"]
    .astype(str)
)

monthly_disbursement

   disbursement_date  loans  disbursement_amount    month
0            2023-12     30            5484000.0  2023-12
1            2024-01   1542          227957000.0  2024-01
2            2024-02   1899          281958000.0  2024-02
3            2024-03   2058          307094000.0  2024-03
4            2024-04   1992          292695000.0  2024-04
5            2024-05   2022          309399000.0  2024-05
6            2024-06   1931          286798000.0  2024-06
7            2024-07   2160          328155000.0  2024-07
8            2024-08   2066          312566000.0  2024-08
9            2024-09   2011          296137000.0  2024-09
10           2024-10   2091          308995000.0  2024-10
11           2024-11   2034          298781000.0  2024-11
12           2024-12   2018          298410000.0  2024-12
13           2025-01   2105          313992000.0  2025-01
14           2025-02   1922          298274000.0  2025-02
15           2025-03   2043          303256000.0  2025-03
16           2025-04   2023          302656000.0  2025-04
17           2025-05   2043          302402000.0  2025-05
18           2025-06   1979          298638000.0  2025-06
19           2025-07   2080          304155000.0  2025-07
20           2025-08   2046          300745000.0  2025-08
21           2025-09   1977          295157000.0  2025-09
22           2025-10   2083          313650000.0  2025-10
23           2025-11   1962          296777000.0  2025-11
24           2025-12   2585          387802000.0  2025-12

In [26]:
loan_monthly_risk = (
    loans_unique
    .merge(
        loan_default,
        on="loan_id",
        how="left"
    )
)

loan_monthly_risk["disbursement_date"] = pd.to_datetime(
    loan_monthly_risk["disbursement_date"]
)

loan_monthly_risk["month"] = (
    loan_monthly_risk["disbursement_date"]
    .dt.to_period("M")
)

monthly_risk = (
    loan_monthly_risk
    .groupby("month")
    .agg(
        loans=("loan_id", "nunique"),
        defaulted_loans=("default_flag", "sum")
    )
    .reset_index()
)

monthly_risk["default_rate"] = (
    monthly_risk["defaulted_loans"]
    / monthly_risk["loans"] * 100
)

monthly_risk

      month  loans  defaulted_loans  default_rate
0   2023-12     30              1.0      3.333333
1   2024-01   1542            130.0      8.430610
2   2024-02   1899            163.0      8.583465
3   2024-03   2058            173.0      8.406220
4   2024-04   1992            151.0      7.580321
5   2024-05   2022            179.0      8.852621
6   2024-06   1931            166.0      8.596582
7   2024-07   2160            150.0      6.944444
8   2024-08   2066            152.0      7.357212
9   2024-09   2011            152.0      7.558429
10  2024-10   2091            148.0      7.077953
11  2024-11   2034            151.0      7.423795
12  2024-12   2018            158.0      7.829534
13  2025-01   2105            120.0      5.700713
14  2025-02   1922            103.0      5.359001
15  2025-03   2043             88.0      4.307391
16  2025-04   2023             68.0      3.361345
17  2025-05   2043             83.0      4.062653
18  2025-06   1979             57.0      2.880243
19  2025-07   2080             50.0      2.403846
20  2025-08   2046             42.0      2.052786
21  2025-09   1977             29.0      1.466869
22  2025-10   2083             14.0      0.672108
23  2025-11   1962              3.0      0.152905
24  2025-12   2585              0.0      0.000000